# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
Rails/StrongParametersExpect:
  Enabled: false
